version: '2.4'
 
services:
    logstash:
      image: docker.elastic.co/logstash/logstash:7.10.1
      ports:
        - "8080:8080"
      command: --config.reload.automatic
      volumes:
        - ./logstash.yml:/usr/share/logstash/config/logstash.yaml:ro
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
